# This is the default configuration file for pass-winmenu.
# If your password store is is located at %userprofile%\.password-store
# and GPG and Git are accessible from your PATH, this settings file will work
# out of the box. Otherwise, you'll have to tweak it a bit.

# All values in this file are set to pass-winmenu's default settings,
# so feel free to delete them from this file; they're only here
# for your reference.
password-store: '%userprofile%\.password-store'
# A regex string against which all filenames in the password directory are 
# compared. All matching files are considered password files.
password-file-match: '.*\.gpg$'
# Path to the GPG executable. Can be either a command name (if GPG is added
# to your PATH) or an absolute directory.
gpg-path: 'gpg'
# Path to the Git executable.
git-path: 'git'
# Amount of time (in seconds) your passwords should remain on the clipboard.
clipboard-timeout: 30
# The directory separator that will be used to separate directories and files
# in the password menu. It's purely a visual indicator, so it can be set to
# whatever character (or sequence of characters) you like.
directory-separator: '/'
# If set to true, only the first line in a decrypted password file will be
# copied to the clipboard. This is the recommended behaviour, as many password
# managers for pass will work the same way.
first-line-only: true
# If set to true, the menu will be opened on the same screen the mouse cursor
# is currently on. If set to false, it will be opened on the primary screen.
follow-cursor: true

output:
    # If your keyboard has dead keys enabled (type ' + e for é), this should
    # be set to true, otherwise usernames/passwords might not be entered
    # correctly.
    dead-keys: false

# Here you can map hotkeys to various actions. Supported actions are:
# - decrypt-password
# - add-password
# - git-pull
# - git-push
# Actions can be further configured using the 'options' variable. 
# Valid options for 'decrypt-password' are:
# - copy-to-clipboard: (true/false)
# - type-username: (true/false)
# - type-password: (true/false)
# The other actions currently have no configurable options.
#
# The default configuration has one hotkey for copying the password to your
# clipboard, and one hotkey for automatically entering your username and
# password into the topmost window.
hotkeys:
  - 
    hotkey: 'ctrl alt p'
    action: 'decrypt-password'
    options:
        copy-to-clipboard: true
        type-username: false
        type-password: false
  - 
    hotkey: 'ctrl alt shift p'
    action: 'decrypt-password'
    options:
        copy-to-clipboard: true
        type-username: true
        type-password: true
# Example configuration of an 'add password' hotkey. Uncomment to enable.
#  - 
#    hotkey: 'ctrl alt o'
#    action: 'add-password'

# If you have added a hotkey where pass-winmenu enters a username and
# a password, you can choose here how you want the application to determine
# the correct username. Uncomment whichever method you prefer to enable it.
# Make sure the other methods are commented out!
username-detection:
    # Use the filename of the password file as the username
#    method: 'filename'

    # Read the text on a specified line in the password file and use that
    # as the username. Note that reading line number 1 (the password line)
    # is not supported.
#    method: 'line-number'
#    options:
#        line-number: 2

    # Use a regex to extract the username from the password file.
    # The username should be placed in a capturing group named 'username',
    # which can be done by putting ?<username> at the beginning of the
    # capturing group.
    method: 'regex'
    options:
        regex: '^[Uu]sername: ((?<username>.*)\r|(?<username>.*))$'
        regex-options:
            ignore-case: false
            multiline: true
            singleline: false

# All colour strings must be formatted as hexadecimal ARGB strings,
# such as #AA00FF44. To 'unset' a colour, a fully transparent colour
# can be used, which is any colour starting with #00.
style:
    orientation: 'vertical'
    font-size: 14
    font-family: 'Consolas'
    background-colour: '#FF202020'
    caret-colour: '#FFDDDDDD'
    # Offset and dimensions of the menu.
    offset-left: 40%
    offset-top: 40%
    width: 20%
    height: 20%

    # This determines the styling of the search text.
    search:
        text-colour: '#FFDDDDDD'
        background-colour: '#00FFFFFF'
        border-colour: '#FF000000'
        border-width: 0
    # This determines the styling of all unselected options.
    options:
        text-colour: '#FFDDDDDD'
        background-colour: '#00FFFFFF'
        border-colour: '#FF000000'
        border-width: 0
    # This determines the styling of the current selection.
    selection:
        text-colour: '#FFFFFFFF'
        background-colour: '#FFD88900'
        border-colour: '#FF000000'
        border-width: 0
